[2024-11-05T16:30:07.212+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T16:30:07.226+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_store_region.run_create_store_region manual__2024-11-05T16:24:58.845436+00:00 [queued]>
[2024-11-05T16:30:07.233+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_store_region.run_create_store_region manual__2024-11-05T16:24:58.845436+00:00 [queued]>
[2024-11-05T16:30:07.233+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-05T16:30:07.244+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_create_store_region> on 2024-11-05 16:24:58.845436+00:00
[2024-11-05T16:30:07.253+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T16:30:07.255+0000] {standard_task_runner.py:72} INFO - Started process 1148 to run task
[2024-11-05T16:30:07.255+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_store_region', 'run_create_store_region', 'manual__2024-11-05T16:24:58.845436+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/create_store_region.py', '--cfg-path', '/tmp/tmpqrwizwlk']
[2024-11-05T16:30:07.256+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_create_store_region
[2024-11-05T16:30:07.299+0000] {task_command.py:467} INFO - Running <TaskInstance: create_store_region.run_create_store_region manual__2024-11-05T16:24:58.845436+00:00 [running]> on host 981fa5312137
[2024-11-05T16:30:07.368+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_store_region' AIRFLOW_CTX_TASK_ID='run_create_store_region' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T16:24:58.845436+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T16:24:58.845436+00:00'
[2024-11-05T16:30:07.369+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-05T16:30:07.370+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-05T16:30:07.370+0000] {logging_mixin.py:190} INFO - Current task name:run_create_store_region state:running start_date:2024-11-05 16:30:07.227176+00:00
[2024-11-05T16:30:07.370+0000] {logging_mixin.py:190} INFO - Dag name:create_store_region and current dag run status:running
[2024-11-05T16:30:07.370+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T16:30:07.371+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_store_region.py", line 38, in main
    'store_region': create_table('store_region')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_store_region.py", line 23, in create_table
    with my_sql_engine().connect() as conn:
         ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_store_region.py", line 9, in my_sql_engine
    return create_engine('mysql+pymysql://myuser:mypassword@localhost/diy')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 80, in dbapi
    return __import__("pymysql")
           ^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pymysql'
[2024-11-05T16:30:07.385+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-05T16:30:07.386+0000] {logging_mixin.py:190} INFO - Task start:2024-11-05 16:30:07.227176+00:00 end:2024-11-05 16:30:07.385326+00:00 duration:0.15815
[2024-11-05T16:30:07.386+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_create_store_region> dag:<DAG: create_store_region> dagrun:<DagRun create_store_region @ 2024-11-05 16:24:58.845436+00:00: manual__2024-11-05T16:24:58.845436+00:00, state:running, queued_at: 2024-11-05 16:24:58.870223+00:00. externally triggered: True>
[2024-11-05T16:30:07.386+0000] {logging_mixin.py:190} INFO - Failure caused by No module named 'pymysql'
[2024-11-05T16:30:07.387+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=create_store_region, task_id=run_create_store_region, run_id=manual__2024-11-05T16:24:58.845436+00:00, execution_date=20241105T162458, start_date=20241105T163007, end_date=20241105T163007
[2024-11-05T16:30:07.397+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T16:30:07.398+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task run_create_store_region (No module named 'pymysql'; 1148)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_store_region.py", line 38, in main
    'store_region': create_table('store_region')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_store_region.py", line 23, in create_table
    with my_sql_engine().connect() as conn:
         ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_store_region.py", line 9, in my_sql_engine
    return create_engine('mysql+pymysql://myuser:mypassword@localhost/diy')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 80, in dbapi
    return __import__("pymysql")
           ^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pymysql'
[2024-11-05T16:30:07.430+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T16:30:07.444+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T16:30:07.446+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
